# Change these first
owner: sensebox # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: senseBox
    url: https://sensebox.de
  - name: senseBox Docs
    url: https://docs.sensebox.de
  - name: Blockly
    url: https://blockly.sensebox.de/ardublockly/?board=sensebox-mcu
  - name: Blockly API
    url: https://api.blockly.sensebox.de/tutorial/
  - name: openSenseMap
    url: https://opensensemap.org
  - name: openSenseMap API
    url: https://api.opensensemap.org
  - name: openSenseMap Archive
    url: https://archive.opensensemap.org/
  - name: Compiler
    method: POST
    url: https://compiler.sensebox.de/compile
    headers:
      - "Content-type: application/json"
    body: '{"board":"sensebox-mcu", "sketch":"void setup() {\nSerial.begin(9600);\nSerial.println(\"Hello World\");\n}\nvoid loop() {}"}'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sensebox.de
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/sensebox/upptime/master/sensebox_logo.svg
  name: senseBox/openSenseMap Status Page
  introTitle: "senseBox and openSenseMap service page"
  introMessage: On this page you can find a status monitoring for all senseBox/openSenseMap Services. If any service is down please have a look at the corresponding issue. If you are experiencing a service outage and do not see it post here, [submit a Support Request](mailto:support@sensebox.de) to get in touch with our Team. The service is powered by Github Actions and Upptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
